# Generated by Django 3.1 on 2020-08-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_likes_pizzeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pizza_type',
            field=models.CharField(choices=[('MEET', 'Has Meet'), ('VEGGIE', 'Vegetarian'), ('VEGAN', 'Vegan')], default=('MEET', 'Has Meet'), max_length=240),
        ),
    ]
